#!/usr/bin/env php
<?php

require_once __DIR__ . "/vendor/autoload.php";
require_once __DIR__ . "/bootstrap/app.php";

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

$app = createApp();

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
